version: '3.8'

services:
  php_what_is_where:
    hostname: what_is_where
    build: docker/php/.
    image: php_what_is_where:fpm-alpine
    container_name: php_what_is_where
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - docker_server_caddy
    ports:
      - "${HTTP_PORT}:9000"

networks:
  docker_server_caddy:
    external: true