version: '3.8'

services:
  php_what_is_where:
    hostname: what_is_where
    image: php:8.3-fpm-alpine
    container_name: php_what_is_where
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - caddy_net
    ports:
      - "${HTTP_PORT}:9000"

networks:
  caddy_net:
    external: true